FROM node:22-bookworm

COPY app/ /app

WORKDIR /app

ENV SMTP_HOST=$SMTP_HOST
ENV SMTP_PORT=$SMTP_PORT
ENV SMTP_USERNAME=$SMTP_USERNAME
ENV SMTP_PASSWORD=$SMTP_PASSWORD
ENV FE_URL=$FE_URL

RUN yarn install

CMD ["yarn", "start"]